[providers]
python = "latest"

[phases.setup]
nixPkgs = ["python310", "libglvnd", "libGL", "glib", "mesa"]

[phases.build]
cmds = ["python -m venv venv", "source venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"
